# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kitty Z Xu
tagline:          personal and professional
url:              http://getpoole.com
paginate:         1
baseurl:          /kittyzxu-github
author:
  name:           KittyZ Xu
  url:            https://twitter.com/mdo
  email:          kitty.zhexu@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
